from dataclasses import dataclass, field
from typing import Optional, List, Dict, Tuple

# ─────────────────────────────────────────────────────────────────────────────
# End-Term / Pipeline State Models (Backward Compatible)
# ─────────────────────────────────────────────────────────────────────────────

@dataclass
class APState:
    """Represents the configuration and state of an Access Point."""
    ap_id: str
    channel: int
    channel_width: int  # in MHz (e.g., 20, 40, 80)
    base_noise: float = -95.0
    x: float = 0.0
    y: float = 0.0
    freq_mhz: float = 5180.0
    tx_power_dbm: float = 20.0
    channel_capacity_mbps: float = 300.0
    
    # Iteration 1 Extensions
    spatial_streams: int = 2
    guard_interval_us: float = 0.8
    antenna_gain_dbi: float = 3.0
    noise_figure_db: float = 5.0
    bss_color: int = 1


@dataclass
class ClientState:
    """Represents a connected client."""
    client_id: str
    demand_mbps: float
    x: float = 0.0
    y: float = 0.0
    wall_count: int = 0
    
    # Iteration 1 Extensions
    velocity_mps: float = 0.0
    direction_rad: float = 0.0
    device_type: str = "laptop"
    application_type: str = "browsing"
    antenna_gain_dbi: float = 0.0
    noise_figure_db: float = 7.0
    mobility_model: str = "stationary"


@dataclass
class QoE:
    """Quality of Experience category and score."""
    score: float
    category: str


@dataclass
class InterferenceEvent:
    """Models an external interference event (e.g., Microwave, BLE)."""
    event_type: str
    noise_boost_db: float
    airtime_boost_percent: float
    duration_minutes: int
    active: bool = False


# ─────────────────────────────────────────────────────────────────────────────
# New Iteration 1 Models
# ─────────────────────────────────────────────────────────────────────────────

@dataclass
class PhyMetrics:
    """Output metrics from the Physical (PHY) Layer for a single client."""
    rssi_dbm: float
    noise_floor_dbm: float
    interference_power_dbm: float
    sinr_db: float
    mcs_index: int
    spatial_streams: int
    guard_interval_us: float
    phy_rate_mbps: float
    per: float  # Packet Error Rate


# -- Digital Twin State Models --

@dataclass
class APDigitalTwin:
    ap_id: str
    channel: int
    channel_width_mhz: int
    tx_power_dbm: float
    antenna_gain_dbi: float
    noise_figure_db: float
    bss_color: int
    x: float
    y: float

@dataclass
class ClientDigitalTwin:
    client_id: str
    ap_id: str
    x: float
    y: float
    velocity_mps: float
    direction_rad: float
    device_type: str
    application_type: str
    demand_mbps: float
    antenna_gain_dbi: float
    noise_figure_db: float
    mobility_model: str
    historical_success_rate: float = 1.0
    recent_retry_rates: List[float] = field(default_factory=list)

@dataclass
class ChannelStateTwin:
    path_loss_db: float
    shadow_loss_db: float
    fast_fading_db: float
    doppler_shift_hz: float

@dataclass
class InterferenceSourceTwin:
    source_id: str
    interference_type: str
    frequency_mhz: float
    bandwidth_mhz: float
    power_dbm: float
    duty_cycle: float
    x: float
    y: float

@dataclass
class DigitalTwinState:
    """Single source of truth tracking APs, clients, channel states, and active interference."""
    aps: Dict[str, APDigitalTwin] = field(default_factory=dict)
    clients: Dict[str, ClientDigitalTwin] = field(default_factory=dict)
    # Key: (ap_id, client_id)
    channel_states: Dict[Tuple[str, str], ChannelStateTwin] = field(default_factory=dict)
    interference_sources: List[InterferenceSourceTwin] = field(default_factory=list)


# ─────────────────────────────────────────────────────────────────────────────
# Telemetry Output
# ─────────────────────────────────────────────────────────────────────────────

@dataclass
class TelemetryRecord:
    """The final telemetry output generated by the simulator."""
    ap_id: str
    channel: int
    client_count: int
    rssi: float
    noise_floor: float
    snr: float
    airtime_utilization: float
    retry_rate: float
    qoe_score: float
    qoe_category: str
    interference_type: str = "None"
    distance: float = 0.0
    freq_mhz: float = 5180.0
    tx_power: float = 20.0
    wall_count: int = 0
    wall_loss: float = 0.0
    recommendations: list = None
    
    # Iteration 1 Extensions (Nullable for backward compatibility)
    sinr: Optional[float] = None
    mcs_index: Optional[int] = None
    phy_rate_mbps: Optional[float] = None
    per: Optional[float] = None
    latency_ms: Optional[float] = None
    throughput_mbps: Optional[float] = None
    
    # Iteration 4 Extension: Sensing Radio
    sensing_report: Optional[dict] = None

    def to_dict(self) -> dict:
        d = {
            "ap_id": self.ap_id,
            "channel": self.channel,
            "client_count": self.client_count,
            "rssi": round(self.rssi, 2),
            "noise_floor": round(self.noise_floor, 2),
            "snr": round(self.snr, 2),
            "airtime_utilization": round(self.airtime_utilization, 2),
            "retry_rate": round(self.retry_rate, 4),
            "qoe_score": round(self.qoe_score, 1),
            "qoe_category": self.qoe_category,
            "interference_type": self.interference_type,
            "distance": round(self.distance, 2),
            "freq_mhz": round(self.freq_mhz, 1),
            "tx_power": round(self.tx_power, 1),
            "wall_count": self.wall_count,
            "wall_loss": round(self.wall_loss, 2),
            "recommendations": self.recommendations or []
        }
        
        # Add new fields if they exist
        if self.sinr is not None:
            d["sinr"] = round(self.sinr, 2)
        if self.mcs_index is not None:
            d["mcs_index"] = self.mcs_index
        if self.phy_rate_mbps is not None:
            d["phy_rate_mbps"] = round(self.phy_rate_mbps, 2)
        if self.per is not None:
            d["per"] = round(self.per, 4)
        if self.latency_ms is not None:
            d["latency_ms"] = round(self.latency_ms, 2)
        if self.throughput_mbps is not None:
            d["throughput_mbps"] = round(self.throughput_mbps, 2)
            
        return d
