from dataclasses import dataclass
from typing import Optional

@dataclass
class APState:
    """Represents the configuration and state of an Access Point."""
    ap_id: str
    channel: int
    channel_width: int  # in MHz (e.g., 20, 40, 80)
    base_noise: float = -95.0

@dataclass
class ClientState:
    """Represents a connected client."""
    client_id: str
    distance_meters: float
    demand_mbps: float

@dataclass
class QoE:
    """Quality of Experience category and score."""
    score: float
    category: str

@dataclass
class InterferenceEvent:
    """Models an external interference event (e.g., Microwave, BLE)."""
    event_type: str
    noise_boost_db: float
    airtime_boost_percent: float
    duration_minutes: int
    active: bool = False

@dataclass
class TelemetryRecord:
    """The final telemetry output generated by the simulator."""
    ap_id: str
    channel: int
    client_count: int
    rssi: float
    noise_floor: float
    snr: float
    airtime_utilization: float
    retry_rate: float
    qoe_score: float
    qoe_category: str
    recommendation: str

    def to_dict(self) -> dict:
        return {
            "ap_id": self.ap_id,
            "channel": self.channel,
            "client_count": self.client_count,
            "rssi": round(self.rssi, 2),
            "noise_floor": round(self.noise_floor, 2),
            "snr": round(self.snr, 2),
            "airtime_utilization": round(self.airtime_utilization, 2),
            "retry_rate": round(self.retry_rate, 4),
            "qoe_score": round(self.qoe_score, 1),
            "qoe_category": self.qoe_category,
            "recommendation": self.recommendation
        }
