from dataclasses import dataclass
from typing import Optional

@dataclass
class APState:
    """Represents the configuration and state of an Access Point."""
    ap_id: str
    channel: int
    channel_width: int  # in MHz (e.g., 20, 40, 80)
    base_noise: float = -95.0
    x: float = 0.0
    y: float = 0.0
    freq_mhz: float = 5180.0
    tx_power_dbm: float = 20.0
    channel_capacity_mbps: float = 300.0

@dataclass
class ClientState:
    """Represents a connected client."""
    client_id: str
    demand_mbps: float
    x: float = 0.0
    y: float = 0.0
    wall_count: int = 0

@dataclass
class QoE:
    """Quality of Experience category and score."""
    score: float
    category: str

@dataclass
class InterferenceEvent:
    """Models an external interference event (e.g., Microwave, BLE)."""
    event_type: str
    noise_boost_db: float
    airtime_boost_percent: float
    duration_minutes: int
    active: bool = False

@dataclass
class TelemetryRecord:
    """The final telemetry output generated by the simulator."""
    ap_id: str
    channel: int
    client_count: int
    rssi: float
    noise_floor: float
    snr: float
    airtime_utilization: float
    retry_rate: float
    qoe_score: float
    qoe_category: str
    interference_type: str = "None"
    distance: float = 0.0
    freq_mhz: float = 5180.0
    tx_power: float = 20.0
    wall_count: int = 0
    wall_loss: float = 0.0
    recommendations: list = None

    def to_dict(self) -> dict:
        return {
            "ap_id": self.ap_id,
            "channel": self.channel,
            "client_count": self.client_count,
            "rssi": round(self.rssi, 2),
            "noise_floor": round(self.noise_floor, 2),
            "snr": round(self.snr, 2),
            "airtime_utilization": round(self.airtime_utilization, 2),
            "retry_rate": round(self.retry_rate, 4),
            "qoe_score": round(self.qoe_score, 1),
            "qoe_category": self.qoe_category,
            "interference_type": self.interference_type,
            "distance": round(self.distance, 2),
            "freq_mhz": round(self.freq_mhz, 1),
            "tx_power": round(self.tx_power, 1),
            "wall_count": self.wall_count,
            "wall_loss": round(self.wall_loss, 2),
            "recommendations": self.recommendations or []
        }
