import datetime
from sqlalchemy import Column, Integer, Float, String, DateTime
from src.database.connection import Base

class Telemetry(Base):
    """
    Model representing raw WiFi Access Point telemetry data.
    """
    __tablename__ = "telemetry"

    id = Column(Integer, primary_key=True, index=True, autoincrement=True)
    timestamp = Column(DateTime, default=datetime.datetime.utcnow, index=True, nullable=False)
    ap_id = Column(String(50), index=True, nullable=False)
    channel = Column(Integer, nullable=False)
    rssi = Column(Float, nullable=False)             # Client RSSI average (dBm)
    snr = Column(Float, nullable=False)              # Client SNR average (dB)
    noise_floor = Column(Float, nullable=False)      # Noise floor (dBm)
    airtime_utilization = Column(Float, nullable=False) # Airtime occupancy (0.0 to 1.0)
    retry_rate = Column(Float, nullable=False)       # Packet retry rate (0.0 to 1.0)
    client_count = Column(Integer, nullable=False)   # Number of active clients
    
    # Realistic Simulator Fields
    qoe_score = Column(Float, nullable=True)         # Calculated QoE 0-100
    qoe_category = Column(String(50), nullable=True) # Excellent, Good, Fair, Poor
    interference_type = Column(String(50), nullable=True) # None, Microwave, BLE, NeighborAP

    def __repr__(self):
        return f"<Telemetry ap_id={self.ap_id} timestamp={self.timestamp} channel={self.channel}>"


class Alert(Base):
    """
    Model representing anomalous network behavior alerts detected by the Change Detection Engine.
    """
    __tablename__ = "alerts"

    id = Column(Integer, primary_key=True, index=True, autoincrement=True)
    timestamp = Column(DateTime, default=datetime.datetime.utcnow, index=True, nullable=False)
    ap_id = Column(String(50), index=True, nullable=False)
    alert_type = Column(String(50), nullable=False)  # e.g., "abnormal_interference", "retry_spike", "airtime_congestion"
    metric = Column(String(50), nullable=False)      # e.g., "noise_floor", "retry_rate", "airtime_utilization"
    value = Column(Float, nullable=False)            # Observed value during anomaly
    threshold = Column(Float, nullable=False)        # Threshold that was violated
    description = Column(String(255), nullable=False)

    def __repr__(self):
        return f"<Alert ap_id={self.ap_id} type={self.alert_type} metric={self.metric}>"


class Recommendation(Base):
    """
    Model representing Radio Resource Management (RRM) action recommendations generated by the Policy Engine.
    """
    __tablename__ = "recommendations"

    id = Column(Integer, primary_key=True, index=True, autoincrement=True)
    timestamp = Column(DateTime, default=datetime.datetime.utcnow, index=True, nullable=False)
    ap_id = Column(String(50), index=True, nullable=False)
    action = Column(String(50), nullable=False)              # e.g., "CHANNEL_CHANGE", "POWER_ADJUST", "WIDTH_ADJUST"
    current_value = Column(String(50), nullable=False)       # Current setting (e.g., "6", "15dBm", "80MHz")
    recommended_value = Column(String(50), nullable=False)   # Recommended setting (e.g., "11", "12dBm", "40MHz")
    confidence = Column(Float, nullable=False)               # Policy rule score / confidence (0.0 to 1.0)
    reason = Column(String(500), nullable=False)             # Descriptive reason explaining the recommendation

    def __repr__(self):
        return f"<Recommendation ap_id={self.ap_id} action={self.action} recommended_value={self.recommended_value}>"
